### ISSUE TITLE
 Can you share the code for generating the Gaussian grasp map?

### ISSUE THREAD

**Issue by ZhiyangZhou24** [wtprew/grasping_robot#1]
Thanks to the author for sharing this excellent work, I was wondering if you would share the code for generating the Gaussian grasp map?

**Comment by wtprew** [comment]
I've uploaded the training scripts which include the Gausssian grasp maps under src/data_loaders. However, this is modified code from https://github.com/nickgkan/orange so I encourage you to check out their work for the original implementation.
